### ISSUE TITLE
Double Quote & Copyright

### ISSUE THREAD

**Issue by klgrimley** [pjaudiomv/jft#8]
Issue seems to be caused when JFT site doesn't properly close a tag. Initially presented when an <i> wasn't closed properly in the content of the meditation. This could become more of a problem if the bad markup occurred in an early section of the meditation.

**Comment by radius314** [comment]
I have this issue too.

**Comment by klgrimley** [comment]
Need to run a check on all remaining tags after the initial scrape and processing that checks for two of the same opening tags in a row instead of an opening followed by a closing and then have it rewrite the offender as a closing. This will most likely be it's own function that the gets called just prior to final output. On my todo list.

**Comment by pjaudiomv** [comment]
I haven't seen this pop up yet with latest version, but not sure that i should close this just yet.

**Comment by radius314** [comment]
Happening on crossroadsarea.org

**Comment by pjaudiomv** [comment]
ok. are they on the most current version, and if so can you be certain its happened since they've updated.

**Comment by radius314** [comment]
On the latest

**Comment by pjaudiomv** [comment]
1.3.1 gotcha, I don't see it there now, but I haven't been checking everyday. Ill have to do this, if by some chance you notice it please let me know if you think of it.

**Comment by pjaudiomv** [comment]
I'm closing this I checked this almost every day for  year, PHP DOM is really good at handling garbage.
